services:
  db:
    image: postgres:15-alpine
    container_name: juscash_db
    environment:
      POSTGRES_USER: juscash
      POSTGRES_PASSWORD: juscash123
      POSTGRES_DB: juscash_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U juscash"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - juscash_network

  redis:
    image: redis:7-alpine
    container_name: juscash_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - juscash_network

  web:
    build: .
    container_name: juscash_web
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://juscash:juscash123@db:5432/juscash_db
      - REDIS_URL=redis://redis:6379/0
      - FLASK_ENV=production
      - SECRET_KEY=your-secret-key-here
    volumes:
      - .:/app
      - ./logs:/app/logs
    command: ["./wait-for-it.sh", "db", "--", "python", "run.py"]
    restart: unless-stopped
    networks:
      - juscash_network

volumes:
  postgres_data:
    driver: local

networks:
  juscash_network:
    driver: bridge 