name: Deploy with Password

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASSWORD }}
        script: |
          cd /var/www/juscash
          
          # Deploy simples
          git pull origin master
          docker-compose down
          docker-compose build --no-cache
          docker-compose up -d
          
          echo "✅ Deploy concluído!" 